baseURL = "https://silly-noether-1833a5.netlify.app"
languageCode = "en-us"
languageName = "En"
paginate = "5"
disqusShortname = "ruthchernous"
theme = "persian"
title = "Ruth Chernous' Wellness Blog"
[markup.goldmark.renderer]
unsafe = true
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Blog"
url = "blog"
weight = 2
[[menu.main]]
name = "About"
url = "about"
weight = 3
[[menu.main]]
name = "Contact"
url = "contact"
weight = 4
[outputs]
home = ["HTML", "RSS", "json"]
[params]
author = "Ruth Chernous"
contact_form_action = "https://formspree.io/f/mjvjvjlr"
copyright = ""
description = "Get fit and healthy to improve your overall life and attract success. Learn how to accept yourself and solve problems one at a time."
logo = "images/logo.svg"
search = true
[params.cookies]
enable = true
expire_days = 2
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[params.preloader]
enable = true
preloader = ""
