baseURL = "https://ruthchernous.com"
languageCode = "en-us"
languageName = "En"
paginate = "6"
disqusShortname = "ruthchernous"
theme = "persian"
title = "Ruth Chernous"
cloudinaryUrl ="https://res.cloudinary.com/ruthchernous"
[markup.goldmark.renderer]
unsafe = true
# [[menu.main]]
# name = "Home"
# url = "/"
# weight = 1

[[menu.main]]
name = "Blog"
url = "/"
weight = 1
[[menu.main]]
name = "About"
url = "about"
weight = 2
[[menu.main]]
name = "Contact"
url = "contact"
weight = 3
[outputs]
home = ["HTML", "RSS", "json"]
[params]
author = "Ruth Chernous"
google_analitycs_id = 'G-TL6MYB6JXJ'
contact_form_action = "https://formspree.io/f/mjvjvjlr"
copyright = "Ruth Chernous"
description = "Personal blog"
logo = "images/logo.svg"

search = true
[params.cookies]
enable = true
expire_days = 2
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[params.preloader]
enable = true
preloader = ""
